In [ ]:
from nhlpy import NHLClient

# Basic usage
client = NHLClient()

# Get all teams
teams = client.teams.teams()
print(teams)

:

In [ ]:
roster = client.teams.team_roster(team_abbr="SJS", season="20252026")
print(f"Forwards: {len(roster['forwards'])}")
print(f"Defensemen: {len(roster['defensemen'])}")
print(f"Goalies: {len(roster['goalies'])}")
print(roster['forwards'])
# Macklin ID: 8484801
sharksfwds = []
for each in roster['forwards']:
  fname = str(each['firstName']['default'])
  lname = str(each['lastName']['default'])
  id = each['id']
  fullname = fname + ' ' + lname
  playerdict = {'id': id, 'name' : fullname}
  sharksfwds.append(playerdict)

print(sharksfwds)

:

In [ ]:
# Get current season skater stats
stats = client.stats.skater_stats_summary(
    start_season="20252026", 
    end_season="20252026"
)

# Show top 5 scorers
for i, player in enumerate(stats[:5]):
    print(f"{i+1}. {player['skaterFullName']}: {player['goals']} goals")
    print(player)

:

In [6]:
import pandas as pd
sharkies = pd.DataFrame(sharksfwds)
print(sharkies)
macky = sharkies[sharkies['name'] == 'Macklin Celebrini']['id'][0]
print(macky)

         id                name
0   8484801   Macklin Celebrini
1   8480848       Ty Dellandrea
2   8482667      William Eklund
3   8478874       Adam Gaudette
4   8476624     Barclay Goodrow
5   8484911         Collin Graf
6   8480798    Philipp Kurashev
7   8485402        Michael Misa
8   8482859      Zack Ostapchuk
9   8471817         Ryan Reaves
10  8483630       Pavol Regenda
11  8475784        Jeff Skinner
12  8484227          Will Smith
13  8475726       Tyler Toffoli
14  8477505  Alexander Wennberg
8484801

In [51]:
import httpx
sharksskatedist = []
for index, row in sharkies.iterrows():
  playerid = row['id']
  
  try:
    skating = client.edge.skater_skating_distance_detail(player_id=playerid, season='20252026')
    skating = skating['skatingDistanceLast10']

    homedist = 0
    awaydist = 0
    for each in skating:
      if each['playerOnHomeTeam'] == True:
        homedist = homedist + each['distanceSkatedAll']['imperial']
      else :
        awaydist = awaydist + each['distanceSkatedAll']['imperial']
 
  except httpx.HTTPStatusError:
        homedist = None
        awaydist = None

  except Exception:
      homedist = None
      awaydist = None
  
  playerdict = {'name' : row['name'], 'homeskatedist' : homedist, 'awayskatedist' : awaydist}
  sharksskatedist.append(playerdict)

sjsskate = pd.DataFrame(sharksskatedist)
display(sjsskate)

                  name  homeskatedist  awayskatedist
0    Macklin Celebrini        17.2001        17.0670
1        Ty Dellandrea        12.2471        12.7033
2       William Eklund        15.6698        15.7553
3        Adam Gaudette         9.7699        10.8479
4      Barclay Goodrow        10.4436         8.4036
5          Collin Graf        11.8850        13.0398
6     Philipp Kurashev        11.9009        12.8026
7         Michael Misa         7.8499         5.7856
8       Zack Ostapchuk         8.0864         4.6386
9          Ryan Reaves         6.9082         6.6573
10       Pavol Regenda            NaN            NaN
11        Jeff Skinner        11.9001         6.4897
12          Will Smith        14.2798        13.8661
13       Tyler Toffoli        10.1559        10.7508
14  Alexander Wennberg        15.0961        14.2588

In [7]:
game_log = client.stats.player_game_log(
    player_id="8484227", 
    season_id="20252026", 
    game_type=2  # Regular season
)

In [10]:
for game in game_log:
  game['commonName'] = game['commonName']['default']
  game['opponentCommonName'] = game['opponentCommonName']['default']
smittygames = pd.DataFrame(game_log)
display(smittygames)

,gameId,teamAbbrev,homeRoadFlag,gameDate,goals,assists,commonName,opponentCommonName,points,plusMinus,...,powerPlayPoints,gameWinningGoals,otGoals,shots,shifts,shorthandedGoals,shorthandedPoints,toi,opponentAbbrev,pim
0,2025020410,SJS,H,2025-12-01,2,1,Sharks,Mammoth,3,2,...,0,1,0,5,20,0,0,19:03,UTA,0
1,2025020400,SJS,R,2025-11-29,2,0,Sharks,Golden Knights,2,0,...,1,0,0,4,23,0,0,19:53,VGK,0
2,2025020385,SJS,H,2025-11-28,1,0,Sharks,Canucks,1,-1,...,1,0,0,3,20,0,0,18:24,VAN,2
3,2025020371,SJS,R,2025-11-26,0,0,Sharks,Avalanche,0,-2,...,0,0,0,4,21,0,0,18:06,COL,0
4,2025020351,SJS,H,2025-11-23,0,0,Sharks,Bruins,0,0,...,0,0,0,7,20,0,0,15:25,BOS,0
5,2025020342,SJS,H,2025-11-22,0,1,Sharks,Senators,1,0,...,1,0,0,2,21,0,0,21:27,OTT,0
6,2025020330,SJS,H,2025-11-20,0,1,Sharks,Kings,1,0,...,0,0,0,1,20,0,0,18:44,LAK,0
7,2025020314,SJS,H,2025-11-18,0,2,Sharks,Mammoth,2,0,...,1,0,0,0,19,0,0,17:23,UTA,0
8,2025020295,SJS,R,2025-11-15,0,0,Sharks,Kraken,0,-3,...,0,0,0,5,19,0,0,19:04,SEA,0
9,2025020276,SJS,R,2025-11-13,0,0,Sharks,Flames,0,-2,...,0,0,0,3,16,0,0,14:27,CGY,0
10,2025020261,SJS,R,2025-11-11,1,0,Sharks,Wild,1,0,...,1,0,0,1,18,0,0,18:31,MIN,0
11,2025020243,SJS,H,2025-11-08,0,2,Sharks,Panthers,2,2,...,0,0,0,2,17,0,0,18:37,FLA,0
12,2025020230,SJS,H,2025-11-07,1,0,Sharks,Jets,1,2,...,0,1,0,4,20,0,0,19:50,WPG,0
13,2025020217,SJS,R,2025-11-05,1,1,Sharks,Kraken,2,2,...,1,0,0,3,17,0,0,14:43,SEA,0
14,2025020198,SJS,H,2025-11-02,0,1,Sharks,Red Wings,1,1,...,0,0,0,1,22,0,0,21:21,DET,0
15,2025020184,SJS,H,2025-11-01,0,0,Sharks,Avalanche,0,1,...,0,0,0,0,24,0,0,20:56,COL,0
16,2025020176,SJS,H,2025-10-30,1,0,Sharks,Devils,1,2,...,0,0,0,2,21,0,0,18:36,NJD,2
17,2025020165,SJS,H,2025-10-28,1,0,Sharks,Kings,1,1,...,0,0,0,3,18,0,0,18:45,LAK,0
18,2025020142,SJS,R,2025-10-26,0,0,Sharks,Wild,0,0,...,0,0,0,2,22,0,0,17:56,MIN,0
19,2025020124,SJS,R,2025-10-24,0,0,Sharks,Devils,0,-1,...,0,0,0,2,21,0,0,20:39,NJD,0
20,2025020116,SJS,R,2025-10-23,2,2,Sharks,Rangers,4,2,...,0,1,1,2,26,0,0,19:40,NYR,2
21,2025020100,SJS,R,2025-10-21,0,0,Sharks,Islanders,0,1,...,0,0,0,4,25,0,0,21:32,NYI,0
22,2025020088,SJS,H,2025-10-18,0,0,Sharks,Penguins,0,0,...,0,0,0,1,15,0,0,13:44,PIT,0
23,2025020075,SJS,R,2025-10-17,0,1,Sharks,Mammoth,1,-2,...,1,0,0,0,16,0,0,12:19,UTA,0
24,2025020055,SJS,H,2025-10-14,0,0,Sharks,Hurricanes,0,-1,...,0,0,0,3,18,0,0,13:57,CAR,2
25,2025020036,SJS,H,2025-10-11,0,3,Sharks,Ducks,3,1,...,1,0,0,3,23,0,0,18:14,ANA,0
26,2025020020,SJS,H,2025-10-09,0,0,Sharks,Golden Knights,0,-1,...,0,0,0,2,20,0,0,20:34,VGK,2

In [ ]:
smittylogs = []
for game in game_log :
  gamedate = game['gameDate']
  goals = game['goals']
  assists = game['assists']
  shots = game['shots']
  toi = game['toi']

[{'gameId': 2025020410,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-12-01',
  'goals': 2,
  'assists': 1,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Mammoth'},
  'points': 3,
  'plusMinus': 2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 1,
  'otGoals': 0,
  'shots': 5,
  'shifts': 20,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '19:03',
  'opponentAbbrev': 'UTA',
  'pim': 0},
 {'gameId': 2025020400,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-11-29',
  'goals': 2,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Golden Knights'},
  'points': 2,
  'plusMinus': 0,
  'powerPlayGoals': 1,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 4,
  'shifts': 23,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '19:53',
  'opponentAbbrev': 'VGK',
  'pim': 0},
 {'gameId': 2025020385,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-28',
  'goals': 1,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Canucks'},
  'points': 1,
  'plusMinus': -1,
  'powerPlayGoals': 1,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 3,
  'shifts': 20,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:24',
  'opponentAbbrev': 'VAN',
  'pim': 2},
 {'gameId': 2025020371,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-11-26',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Avalanche'},
  'points': 0,
  'plusMinus': -2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 4,
  'shifts': 21,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:06',
  'opponentAbbrev': 'COL',
  'pim': 0},
 {'gameId': 2025020351,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-23',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Bruins'},
  'points': 0,
  'plusMinus': 0,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 7,
  'shifts': 20,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '15:25',
  'opponentAbbrev': 'BOS',
  'pim': 0},
 {'gameId': 2025020342,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-22',
  'goals': 0,
  'assists': 1,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Senators', 'fr': 'Sénateurs'},
  'points': 1,
  'plusMinus': 0,
  'powerPlayGoals': 0,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 2,
  'shifts': 21,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '21:27',
  'opponentAbbrev': 'OTT',
  'pim': 0},
 {'gameId': 2025020330,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-20',
  'goals': 0,
  'assists': 1,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Kings'},
  'points': 1,
  'plusMinus': 0,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 1,
  'shifts': 20,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:44',
  'opponentAbbrev': 'LAK',
  'pim': 0},
 {'gameId': 2025020314,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-18',
  'goals': 0,
  'assists': 2,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Mammoth'},
  'points': 2,
  'plusMinus': 0,
  'powerPlayGoals': 0,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 0,
  'shifts': 19,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '17:23',
  'opponentAbbrev': 'UTA',
  'pim': 0},
 {'gameId': 2025020295,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-11-15',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Kraken'},
  'points': 0,
  'plusMinus': -3,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 5,
  'shifts': 19,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '19:04',
  'opponentAbbrev': 'SEA',
  'pim': 0},
 {'gameId': 2025020276,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-11-13',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Flames'},
  'points': 0,
  'plusMinus': -2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 3,
  'shifts': 16,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '14:27',
  'opponentAbbrev': 'CGY',
  'pim': 0},
 {'gameId': 2025020261,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-11-11',
  'goals': 1,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Wild'},
  'points': 1,
  'plusMinus': 0,
  'powerPlayGoals': 1,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 1,
  'shifts': 18,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:31',
  'opponentAbbrev': 'MIN',
  'pim': 0},
 {'gameId': 2025020243,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-08',
  'goals': 0,
  'assists': 2,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Panthers'},
  'points': 2,
  'plusMinus': 2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 2,
  'shifts': 17,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:37',
  'opponentAbbrev': 'FLA',
  'pim': 0},
 {'gameId': 2025020230,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-07',
  'goals': 1,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Jets'},
  'points': 1,
  'plusMinus': 2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 1,
  'otGoals': 0,
  'shots': 4,
  'shifts': 20,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '19:50',
  'opponentAbbrev': 'WPG',
  'pim': 0},
 {'gameId': 2025020217,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-11-05',
  'goals': 1,
  'assists': 1,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Kraken'},
  'points': 2,
  'plusMinus': 2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 3,
  'shifts': 17,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '14:43',
  'opponentAbbrev': 'SEA',
  'pim': 0},
 {'gameId': 2025020198,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-02',
  'goals': 0,
  'assists': 1,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Red Wings'},
  'points': 1,
  'plusMinus': 1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 1,
  'shifts': 22,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '21:21',
  'opponentAbbrev': 'DET',
  'pim': 0},
 {'gameId': 2025020184,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-11-01',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Avalanche'},
  'points': 0,
  'plusMinus': 1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 0,
  'shifts': 24,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '20:56',
  'opponentAbbrev': 'COL',
  'pim': 0},
 {'gameId': 2025020176,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-10-30',
  'goals': 1,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Devils'},
  'points': 1,
  'plusMinus': 2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 2,
  'shifts': 21,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:36',
  'opponentAbbrev': 'NJD',
  'pim': 2},
 {'gameId': 2025020165,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-10-28',
  'goals': 1,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Kings'},
  'points': 1,
  'plusMinus': 1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 3,
  'shifts': 18,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:45',
  'opponentAbbrev': 'LAK',
  'pim': 0},
 {'gameId': 2025020142,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-10-26',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Wild'},
  'points': 0,
  'plusMinus': 0,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 2,
  'shifts': 22,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '17:56',
  'opponentAbbrev': 'MIN',
  'pim': 0},
 {'gameId': 2025020124,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-10-24',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Devils'},
  'points': 0,
  'plusMinus': -1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 2,
  'shifts': 21,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '20:39',
  'opponentAbbrev': 'NJD',
  'pim': 0},
 {'gameId': 2025020116,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-10-23',
  'goals': 2,
  'assists': 2,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Rangers'},
  'points': 4,
  'plusMinus': 2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 1,
  'otGoals': 1,
  'shots': 2,
  'shifts': 26,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '19:40',
  'opponentAbbrev': 'NYR',
  'pim': 2},
 {'gameId': 2025020100,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-10-21',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Islanders'},
  'points': 0,
  'plusMinus': 1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 4,
  'shifts': 25,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '21:32',
  'opponentAbbrev': 'NYI',
  'pim': 0},
 {'gameId': 2025020088,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-10-18',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Penguins'},
  'points': 0,
  'plusMinus': 0,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 1,
  'shifts': 15,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '13:44',
  'opponentAbbrev': 'PIT',
  'pim': 0},
 {'gameId': 2025020075,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'R',
  'gameDate': '2025-10-17',
  'goals': 0,
  'assists': 1,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Mammoth'},
  'points': 1,
  'plusMinus': -2,
  'powerPlayGoals': 0,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 0,
  'shifts': 16,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '12:19',
  'opponentAbbrev': 'UTA',
  'pim': 0},
 {'gameId': 2025020055,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-10-14',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Hurricanes'},
  'points': 0,
  'plusMinus': -1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 3,
  'shifts': 18,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '13:57',
  'opponentAbbrev': 'CAR',
  'pim': 2},
 {'gameId': 2025020036,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-10-11',
  'goals': 0,
  'assists': 3,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Ducks'},
  'points': 3,
  'plusMinus': 1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 1,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 3,
  'shifts': 23,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '18:14',
  'opponentAbbrev': 'ANA',
  'pim': 0},
 {'gameId': 2025020020,
  'teamAbbrev': 'SJS',
  'homeRoadFlag': 'H',
  'gameDate': '2025-10-09',
  'goals': 0,
  'assists': 0,
  'commonName': {'default': 'Sharks'},
  'opponentCommonName': {'default': 'Golden Knights'},
  'points': 0,
  'plusMinus': -1,
  'powerPlayGoals': 0,
  'powerPlayPoints': 0,
  'gameWinningGoals': 0,
  'otGoals': 0,
  'shots': 2,
  'shifts': 20,
  'shorthandedGoals': 0,
  'shorthandedPoints': 0,
  'toi': '20:34',
  'opponentAbbrev': 'VGK',
  'pim': 2}]

In [27]:
client.edge.skater_detail(player_id='8484801', season='20242025')

{'player': {'id': 8484801,
  'firstName': {'default': 'Macklin'},
  'lastName': {'default': 'Celebrini'},
  'birthDate': '2006-06-13',
  'shootsCatches': 'L',
  'sweaterNumber': 71,
  'position': 'C',
  'slug': 'macklin-celebrini-8484801',
  'headshot': 'https://assets.nhle.com/mugs/nhl/20242025/SJS/8484801.png',
  'goals': 25,
  'assists': 38,
  'points': 63,
  'gamesPlayed': 70,
  'team': {'commonName': {'default': 'Sharks'},
   'placeNameWithPreposition': {'default': 'San Jose', 'fr': 'de San Jose'},
   'abbrev': 'SJS',
   'teamLogo': {'light': 'https://assets.nhle.com/logos/nhl/svg/SJS_light.svg',
    'dark': 'https://assets.nhle.com/logos/nhl/svg/SJS_dark.svg'}}},
 'seasonsWithEdgeStats': [{'id': 20242025, 'gameTypes': [2]},
  {'id': 20252026, 'gameTypes': [2]}],
 'topShotSpeed': {'imperial': 89.64,
  'metric': 144.2616,
  'percentile': 0.7677,
  'leagueAvg': {'imperial': 83.9219, 'metric': 135.0592},
  'overlay': {'player': {'firstName': {'default': 'Macklin'},
    'lastName': {'default': 'Celebrini'}},
   'gameDate': '2025-04-11',
   'awayTeam': {'abbrev': 'SJS', 'score': 2},
   'homeTeam': {'abbrev': 'EDM', 'score': 4},
   'gameOutcome': {'lastPeriodType': 'REG'},
   'periodDescriptor': {'maxRegulationPeriods': 3,
    'number': 3,
    'periodType': 'REG'},
   'timeInPeriod': '00:09',
   'gameType': 2}},
 'skatingSpeed': {'speedMax': {'imperial': 23.098,
   'metric': 37.172,
   'percentile': 0.8817,
   'leagueAvg': {'imperial': 22.1829, 'metric': 35.6998},
   'overlay': {'player': {'firstName': {'default': 'Macklin'},
     'lastName': {'default': 'Celebrini'}},
    'gameDate': '2025-01-27',
    'awayTeam': {'abbrev': 'PIT', 'score': 1},
    'homeTeam': {'abbrev': 'SJS', 'score': 2},
    'gameOutcome': {'lastPeriodType': 'REG'},
    'periodDescriptor': {'maxRegulationPeriods': 3,
     'number': 3,
     'periodType': 'REG'},
    'timeInPeriod': '00:21',
    'gameType': 2}},
  'burstsOver20': {'value': 168,
   'percentile': 0.9017,
   'leagueAvg': {'value': 76.4559}}},
 'totalDistanceSkated': {'imperial': 231.9606,
  'metric': 373.2862,
  'percentile': 0.8883,
  'leagueAvg': {'imperial': 127.079, 'metric': 204.5038}},
 'sogSummary': [{'locationCode': 'all',
   'shots': 236,
   'shotsPercentile': 0.96,
   'shotsLeagueAvg': 88.7072,
   'goals': 25,
   'goalsPercentile': 0.8633,
   'goalsLeagueAvg': 11.2479,
   'shootingPctg': 0.1059,
   'shootingPctgPercentile': 0.2177,
   'shootingPctgLeagueAvg': 0.1268},
  {'locationCode': 'high',
   'shots': 48,
   'shotsPercentile': 0.745,
   'shotsLeagueAvg': 30.3744,
   'goals': 9,
   'goalsPercentile': 0.6983,
   'goalsLeagueAvg': 6.1215,
   'shootingPctg': 0.1875,
   'shootingPctgPercentile': 0.3911,
   'shootingPctgLeagueAvg': 0.2015},
  {'locationCode': 'long',
   'shots': 14,
   'shotsPercentile': 0.7833,
   'shotsLeagueAvg': 8.7471,
   'goals': 0,
   'goalsPercentile': 0.0,
   'goalsLeagueAvg': 0.3328,
   'shootingPctg': 0.0,
   'shootingPctgPercentile': 0.0,
   'shootingPctgLeagueAvg': 0.038},
  {'locationCode': 'mid',
   'shots': 119,
   'shotsPercentile': 0.995,
   'shotsLeagueAvg': 28.3211,
   'goals': 10,
   'goalsPercentile': 0.9017,
   'goalsLeagueAvg': 3.3527,
   'shootingPctg': 0.084,
   'shootingPctgPercentile': 0.2768,
   'shootingPctgLeagueAvg': 0.1184}],
 'sogDetails': [{'area': 'Behind the Net',
   'shots': 1,
   'shotsPercentile': 0.5917},
  {'area': 'Beyond Red Line', 'shots': 8, 'shotsPercentile': 0.9783},
  {'area': 'Center Point', 'shots': 4, 'shotsPercentile': 0.6717},
  {'area': 'Crease', 'shots': 3, 'shotsPercentile': 0.46},
  {'area': 'High Slot', 'shots': 34, 'shotsPercentile': 0.9867},
  {'area': 'L Circle', 'shots': 44, 'shotsPercentile': 0.99},
  {'area': 'L Corner', 'shots': 0, 'shotsPercentile': 0.0},
  {'area': 'L Net Side', 'shots': 4, 'shotsPercentile': 0.705},
  {'area': 'L Point', 'shots': 7, 'shotsPercentile': 0.8717},
  {'area': 'Low Slot', 'shots': 45, 'shotsPercentile': 0.7917},
  {'area': 'Offensive Neutral Zone', 'shots': 2, 'shotsPercentile': 0.4983},
  {'area': 'Outside L', 'shots': 11, 'shotsPercentile': 0.8233},
  {'area': 'Outside R', 'shots': 22, 'shotsPercentile': 0.985},
  {'area': 'R Circle', 'shots': 41, 'shotsPercentile': 0.9867},
  {'area': 'R Corner', 'shots': 0, 'shotsPercentile': 0.0},
  {'area': 'R Net Side', 'shots': 7, 'shotsPercentile': 0.8783},
  {'area': 'R Point', 'shots': 3, 'shotsPercentile': 0.5583}],
 'zoneTimeDetails': {'offensiveZonePctg': 0.44209136,
  'offensiveZonePercentile': 0.7802469135802,
  'offensiveZoneLeagueAvg': 0.4234038,
  'neutralZonePctg': 0.17850583,
  'neutralZonePercentile': 0.4987654320988,
  'neutralZoneLeagueAvg': 0.17830407,
  'defensiveZonePctg': 0.37940281,
  'defensiveZonePercentile': 0.7851851851852,
  'defensiveZoneLeagueAvg': 0.39829213}}

In [ ]:
# Get current standings
standings = client.standings.league_standings()
print(standings)

# Get today's games
games = client.schedule.daily_schedule()

{'wildCardIndicator': True, 'standingsDateTimeUtc': '2025-12-01T18:39:45Z', 'standings': [{'conferenceAbbrev': 'W', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 1, 'conferenceName': 'Western', 'conferenceRoadSequence': 3, 'conferenceSequence': 1, 'date': '2025-12-01', 'divisionAbbrev': 'C', 'divisionHomeSequence': 1, 'divisionL10Sequence': 1, 'divisionName': 'Central', 'divisionRoadSequence': 2, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 48, 'goalDifferentialPctg': 1.92, 'goalAgainst': 55, 'goalFor': 103, 'goalsForPctg': 4.12, 'homeGamesPlayed': 12, 'homeGoalDifferential': 30, 'homeGoalsAgainst': 28, 'homeGoalsFor': 58, 'homeLosses': 0, 'homeOtLosses': 2, 'homePoints': 22, 'homeRegulationPlusOtWins': 10, 'homeRegulationWins': 10, 'homeTies': 0, 'homeWins': 10, 'l10GamesPlayed': 10, 'l10GoalDifferential': 27, 'l10GoalsAgainst': 17, 'l10GoalsFor': 44, 'l10Losses': 0, 'l10OtLosses': 1, 'l10Points': 19, 'l10RegulationPlusOtWins': 9, 'l10RegulationWins': 8, 'l10Ties': 0, 'l10Wins': 9, 'leagueHomeSequence': 1, 'leagueL10Sequence': 1, 'leagueRoadSequence': 4, 'leagueSequence': 1, 'losses': 1, 'otLosses': 6, 'placeName': {'default': 'Colorado'}, 'pointPctg': 0.84, 'points': 42, 'regulationPlusOtWinPctg': 0.72, 'regulationPlusOtWins': 18, 'regulationWinPctg': 0.68, 'regulationWins': 17, 'roadGamesPlayed': 13, 'roadGoalDifferential': 18, 'roadGoalsAgainst': 27, 'roadGoalsFor': 45, 'roadLosses': 1, 'roadOtLosses': 4, 'roadPoints': 20, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 7, 'roadTies': 0, 'roadWins': 8, 'seasonId': 20252026, 'shootoutLosses': 3, 'shootoutWins': 0, 'streakCode': 'W', 'streakCount': 1, 'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'}, 'teamCommonName': {'default': 'Avalanche'}, 'teamAbbrev': {'default': 'COL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg', 'ties': 0, 'waiversSequence': 32, 'wildcardSequence': 0, 'winPctg': 0.72, 'wins': 18}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 5, 'conferenceL10Sequence': 3, 'conferenceName': 'Western', 'conferenceRoadSequence': 2, 'conferenceSequence': 2, 'date': '2025-12-01', 'divisionAbbrev': 'C', 'divisionHomeSequence': 3, 'divisionL10Sequence': 3, 'divisionName': 'Central', 'divisionRoadSequence': 1, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 26, 'goalDifferential': 22, 'goalDifferentialPctg': 0.846154, 'goalAgainst': 71, 'goalFor': 93, 'goalsForPctg': 3.576923, 'homeGamesPlayed': 13, 'homeGoalDifferential': 7, 'homeGoalsAgainst': 36, 'homeGoalsFor': 43, 'homeLosses': 4, 'homeOtLosses': 1, 'homePoints': 17, 'homeRegulationPlusOtWins': 7, 'homeRegulationWins': 7, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 24, 'l10GoalsAgainst': 20, 'l10GoalsFor': 44, 'l10Losses': 1, 'l10OtLosses': 1, 'l10Points': 17, 'l10RegulationPlusOtWins': 8, 'l10RegulationWins': 7, 'l10Ties': 0, 'l10Wins': 8, 'leagueHomeSequence': 12, 'leagueL10Sequence': 3, 'leagueRoadSequence': 3, 'leagueSequence': 2, 'losses': 5, 'otLosses': 4, 'placeName': {'default': 'Dallas'}, 'pointPctg': 0.730769, 'points': 38, 'regulationPlusOtWinPctg': 0.576923, 'regulationPlusOtWins': 15, 'regulationWinPctg': 0.538462, 'regulationWins': 14, 'roadGamesPlayed': 13, 'roadGoalDifferential': 15, 'roadGoalsAgainst': 35, 'roadGoalsFor': 50, 'roadLosses': 1, 'roadOtLosses': 3, 'roadPoints': 21, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 7, 'roadTies': 0, 'roadWins': 9, 'seasonId': 20252026, 'shootoutLosses': 2, 'shootoutWins': 2, 'streakCode': 'W', 'streakCount': 4, 'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'}, 'teamCommonName': {'default': 'Stars'}, 'teamAbbrev': {'default': 'DAL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg', 'ties': 0, 'waiversSequence': 31, 'wildcardSequence': 0, 'winPctg': 0.653846, 'wins': 17}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 10, 'conferenceL10Sequence': 1, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 2, 'conferenceSequence': 1, 'date': '2025-12-01', 'divisionAbbrev': 'A', 'divisionHomeSequence': 6, 'divisionL10Sequence': 1, 'divisionName': 'Atlantic', 'divisionRoadSequence': 1, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 19, 'goalDifferentialPctg': 0.76, 'goalAgainst': 65, 'goalFor': 84, 'goalsForPctg': 3.36, 'homeGamesPlayed': 13, 'homeGoalDifferential': 4, 'homeGoalsAgainst': 36, 'homeGoalsFor': 40, 'homeLosses': 5, 'homeOtLosses': 0, 'homePoints': 16, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 5, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 14, 'l10GoalsAgainst': 24, 'l10GoalsFor': 38, 'l10Losses': 2, 'l10OtLosses': 0, 'l10Points': 16, 'l10RegulationPlusOtWins': 8, 'l10RegulationWins': 7, 'l10Ties': 0, 'l10Wins': 8, 'leagueHomeSequence': 15, 'leagueL10Sequence': 4, 'leagueRoadSequence': 5, 'leagueSequence': 3, 'losses': 7, 'otLosses': 2, 'placeName': {'default': 'Tampa Bay'}, 'pointPctg': 0.68, 'points': 34, 'regulationPlusOtWinPctg': 0.64, 'regulationPlusOtWins': 16, 'regulationWinPctg': 0.52, 'regulationWins': 13, 'roadGamesPlayed': 12, 'roadGoalDifferential': 15, 'roadGoalsAgainst': 29, 'roadGoalsFor': 44, 'roadLosses': 2, 'roadOtLosses': 2, 'roadPoints': 18, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 8, 'roadTies': 0, 'roadWins': 8, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 0, 'streakCode': 'W', 'streakCount': 7, 'teamName': {'default': 'Tampa Bay Lightning', 'fr': 'Lightning de Tampa Bay'}, 'teamCommonName': {'default': 'Lightning'}, 'teamAbbrev': {'default': 'TBL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg', 'ties': 0, 'waiversSequence': 30, 'wildcardSequence': 0, 'winPctg': 0.64, 'wins': 16}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 7, 'conferenceL10Sequence': 4, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 3, 'conferenceSequence': 2, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 4, 'divisionL10Sequence': 3, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 2, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 16, 'goalDifferentialPctg': 0.64, 'goalAgainst': 70, 'goalFor': 86, 'goalsForPctg': 3.44, 'homeGamesPlayed': 12, 'homeGoalDifferential': 9, 'homeGoalsAgainst': 36, 'homeGoalsFor': 45, 'homeLosses': 3, 'homeOtLosses': 1, 'homePoints': 17, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 5, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': -1, 'l10GoalsAgainst': 28, 'l10GoalsFor': 27, 'l10Losses': 3, 'l10OtLosses': 2, 'l10Points': 12, 'l10RegulationPlusOtWins': 5, 'l10RegulationWins': 3, 'l10Ties': 0, 'l10Wins': 5, 'leagueHomeSequence': 11, 'leagueL10Sequence': 11, 'leagueRoadSequence': 6, 'leagueSequence': 4, 'losses': 7, 'otLosses': 2, 'placeName': {'default': 'Carolina', 'fr': 'Caroline'}, 'pointPctg': 0.68, 'points': 34, 'regulationPlusOtWinPctg': 0.6, 'regulationPlusOtWins': 15, 'regulationWinPctg': 0.44, 'regulationWins': 11, 'roadGamesPlayed': 13, 'roadGoalDifferential': 7, 'roadGoalsAgainst': 34, 'roadGoalsFor': 41, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 17, 'roadRegulationPlusOtWins': 7, 'roadRegulationWins': 6, 'roadTies': 0, 'roadWins': 8, 'seasonId': 20252026, 'shootoutLosses': 1, 'shootoutWins': 1, 'streakCode': 'W', 'streakCount': 2, 'teamName': {'default': 'Carolina Hurricanes', 'fr': 'Hurricanes de la Caroline'}, 'teamCommonName': {'default': 'Hurricanes'}, 'teamAbbrev': {'default': 'CAR'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg', 'ties': 0, 'waiversSequence': 29, 'wildcardSequence': 0, 'winPctg': 0.64, 'wins': 16}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 9, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 7, 'conferenceSequence': 3, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 1, 'divisionL10Sequence': 7, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 5, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 6, 'goalDifferentialPctg': 0.24, 'goalAgainst': 74, 'goalFor': 80, 'goalsForPctg': 3.2, 'homeGamesPlayed': 11, 'homeGoalDifferential': 11, 'homeGoalsAgainst': 26, 'homeGoalsFor': 37, 'homeLosses': 1, 'homeOtLosses': 1, 'homePoints': 19, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 5, 'homeTies': 0, 'homeWins': 9, 'l10GamesPlayed': 10, 'l10GoalDifferential': -2, 'l10GoalsAgainst': 30, 'l10GoalsFor': 28, 'l10Losses': 4, 'l10OtLosses': 1, 'l10Points': 11, 'l10RegulationPlusOtWins': 4, 'l10RegulationWins': 2, 'l10Ties': 0, 'l10Wins': 5, 'leagueHomeSequence': 3, 'leagueL10Sequence': 17, 'leagueRoadSequence': 14, 'leagueSequence': 5, 'losses': 8, 'otLosses': 1, 'placeName': {'default': 'New Jersey'}, 'pointPctg': 0.66, 'points': 33, 'regulationPlusOtWinPctg': 0.56, 'regulationPlusOtWins': 14, 'regulationWinPctg': 0.4, 'regulationWins': 10, 'roadGamesPlayed': 14, 'roadGoalDifferential': -5, 'roadGoalsAgainst': 48, 'roadGoalsFor': 43, 'roadLosses': 7, 'roadOtLosses': 0, 'roadPoints': 14, 'roadRegulationPlusOtWins': 6, 'roadRegulationWins': 5, 'roadTies': 0, 'roadWins': 7, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 2, 'streakCode': 'L', 'streakCount': 1, 'teamName': {'default': 'New Jersey Devils', 'fr': 'Devils du New Jersey'}, 'teamCommonName': {'default': 'Devils'}, 'teamAbbrev': {'default': 'NJD'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/NJD_light.svg', 'ties': 0, 'waiversSequence': 28, 'wildcardSequence': 0, 'winPctg': 0.64, 'wins': 16}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 2, 'conferenceL10Sequence': 2, 'conferenceName': 'Western', 'conferenceRoadSequence': 8, 'conferenceSequence': 3, 'date': '2025-12-01', 'divisionAbbrev': 'C', 'divisionHomeSequence': 2, 'divisionL10Sequence': 2, 'divisionName': 'Central', 'divisionRoadSequence': 4, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 26, 'goalDifferential': 5, 'goalDifferentialPctg': 0.192308, 'goalAgainst': 72, 'goalFor': 77, 'goalsForPctg': 2.961538, 'homeGamesPlayed': 15, 'homeGoalDifferential': -2, 'homeGoalsAgainst': 46, 'homeGoalsFor': 44, 'homeLosses': 3, 'homeOtLosses': 4, 'homePoints': 20, 'homeRegulationPlusOtWins': 5, 'homeRegulationWins': 3, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 14, 'l10GoalsAgainst': 15, 'l10GoalsFor': 29, 'l10Losses': 0, 'l10OtLosses': 2, 'l10Points': 18, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 4, 'l10Ties': 0, 'l10Wins': 8, 'leagueHomeSequence': 2, 'leagueL10Sequence': 2, 'leagueRoadSequence': 18, 'leagueSequence': 6, 'losses': 7, 'otLosses': 5, 'placeName': {'default': 'Minnesota'}, 'pointPctg': 0.634615, 'points': 33, 'regulationPlusOtWinPctg': 0.423077, 'regulationPlusOtWins': 11, 'regulationWinPctg': 0.307692, 'regulationWins': 8, 'roadGamesPlayed': 11, 'roadGoalDifferential': 7, 'roadGoalsAgainst': 26, 'roadGoalsFor': 33, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 6, 'roadRegulationWins': 5, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 1, 'shootoutWins': 3, 'streakCode': 'OT', 'streakCount': 1, 'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'}, 'teamCommonName': {'default': 'Wild'}, 'teamAbbrev': {'default': 'MIN'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg', 'ties': 0, 'waiversSequence': 26, 'wildcardSequence': 0, 'winPctg': 0.538462, 'wins': 14}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 2, 'conferenceL10Sequence': 2, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 10, 'conferenceSequence': 4, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 2, 'divisionL10Sequence': 1, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 7, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 26, 'goalDifferential': 19, 'goalDifferentialPctg': 0.730769, 'goalAgainst': 69, 'goalFor': 88, 'goalsForPctg': 3.384615, 'homeGamesPlayed': 15, 'homeGoalDifferential': 10, 'homeGoalsAgainst': 41, 'homeGoalsFor': 51, 'homeLosses': 5, 'homeOtLosses': 1, 'homePoints': 19, 'homeRegulationPlusOtWins': 9, 'homeRegulationWins': 8, 'homeTies': 0, 'homeWins': 9, 'l10GamesPlayed': 10, 'l10GoalDifferential': 12, 'l10GoalsAgainst': 30, 'l10GoalsFor': 42, 'l10Losses': 2, 'l10OtLosses': 1, 'l10Points': 15, 'l10RegulationPlusOtWins': 7, 'l10RegulationWins': 7, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 4, 'leagueL10Sequence': 5, 'leagueRoadSequence': 17, 'leagueSequence': 7, 'losses': 9, 'otLosses': 2, 'placeName': {'default': 'Washington'}, 'pointPctg': 0.615385, 'points': 32, 'regulationPlusOtWinPctg': 0.576923, 'regulationPlusOtWins': 15, 'regulationWinPctg': 0.538462, 'regulationWins': 14, 'roadGamesPlayed': 11, 'roadGoalDifferential': 9, 'roadGoalsAgainst': 28, 'roadGoalsFor': 37, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 6, 'roadRegulationWins': 6, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 2, 'shootoutWins': 0, 'streakCode': 'W', 'streakCount': 4, 'teamName': {'default': 'Washington Capitals', 'fr': 'Capitals de Washington'}, 'teamCommonName': {'default': 'Capitals'}, 'teamAbbrev': {'default': 'WSH'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/WSH_secondary_light.svg', 'ties': 0, 'waiversSequence': 23, 'wildcardSequence': 0, 'winPctg': 0.576923, 'wins': 15}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 4, 'conferenceL10Sequence': 3, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 11, 'conferenceSequence': 5, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 3, 'divisionL10Sequence': 2, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 8, 'divisionSequence': 4, 'gameTypeId': 2, 'gamesPlayed': 24, 'goalDifferential': 6, 'goalDifferentialPctg': 0.25, 'goalAgainst': 67, 'goalFor': 73, 'goalsForPctg': 3.041667, 'homeGamesPlayed': 13, 'homeGoalDifferential': 7, 'homeGoalsAgainst': 33, 'homeGoalsFor': 40, 'homeLosses': 3, 'homeOtLosses': 2, 'homePoints': 18, 'homeRegulationPlusOtWins': 6, 'homeRegulationWins': 4, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 1, 'l10GoalsAgainst': 31, 'l10GoalsFor': 32, 'l10Losses': 2, 'l10OtLosses': 2, 'l10Points': 14, 'l10RegulationPlusOtWins': 4, 'l10RegulationWins': 3, 'l10Ties': 0, 'l10Wins': 6, 'leagueHomeSequence': 8, 'leagueL10Sequence': 7, 'leagueRoadSequence': 19, 'leagueSequence': 8, 'losses': 7, 'otLosses': 3, 'placeName': {'default': 'Philadelphia', 'fr': 'Philadelphie'}, 'pointPctg': 0.645833, 'points': 31, 'regulationPlusOtWinPctg': 0.375, 'regulationPlusOtWins': 9, 'regulationWinPctg': 0.291667, 'regulationWins': 7, 'roadGamesPlayed': 11, 'roadGoalDifferential': -1, 'roadGoalsAgainst': 34, 'roadGoalsFor': 33, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 3, 'roadRegulationWins': 3, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 5, 'streakCode': 'W', 'streakCount': 3, 'teamName': {'default': 'Philadelphia Flyers', 'fr': 'Flyers de Philadelphie'}, 'teamCommonName': {'default': 'Flyers'}, 'teamAbbrev': {'default': 'PHI'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/PHI_light.svg', 'ties': 0, 'waiversSequence': 27, 'wildcardSequence': 1, 'winPctg': 0.583333, 'wins': 14}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 4, 'conferenceL10Sequence': 14, 'conferenceName': 'Western', 'conferenceRoadSequence': 10, 'conferenceSequence': 4, 'date': '2025-12-01', 'divisionAbbrev': 'P', 'divisionHomeSequence': 2, 'divisionL10Sequence': 7, 'divisionName': 'Pacific', 'divisionRoadSequence': 6, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 9, 'goalDifferentialPctg': 0.36, 'goalAgainst': 83, 'goalFor': 92, 'goalsForPctg': 3.68, 'homeGamesPlayed': 12, 'homeGoalDifferential': 13, 'homeGoalsAgainst': 34, 'homeGoalsFor': 47, 'homeLosses': 3, 'homeOtLosses': 0, 'homePoints': 18, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 6, 'homeTies': 0, 'homeWins': 9, 'l10GamesPlayed': 10, 'l10GoalDifferential': -8, 'l10GoalsAgainst': 37, 'l10GoalsFor': 29, 'l10Losses': 6, 'l10OtLosses': 0, 'l10Points': 8, 'l10RegulationPlusOtWins': 3, 'l10RegulationWins': 1, 'l10Ties': 0, 'l10Wins': 4, 'leagueHomeSequence': 7, 'leagueL10Sequence': 29, 'leagueRoadSequence': 21, 'leagueSequence': 9, 'losses': 9, 'otLosses': 1, 'placeName': {'default': 'Anaheim'}, 'pointPctg': 0.62, 'points': 31, 'regulationPlusOtWinPctg': 0.52, 'regulationPlusOtWins': 13, 'regulationWinPctg': 0.36, 'regulationWins': 9, 'roadGamesPlayed': 13, 'roadGoalDifferential': -4, 'roadGoalsAgainst': 49, 'roadGoalsFor': 45, 'roadLosses': 6, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 5, 'roadRegulationWins': 3, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 2, 'streakCode': 'L', 'streakCount': 1, 'teamName': {'default': 'Anaheim Ducks', 'fr': "Ducks d'Anaheim"}, 'teamCommonName': {'default': 'Ducks'}, 'teamAbbrev': {'default': 'ANA'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/ANA_light.svg', 'ties': 0, 'waiversSequence': 25, 'wildcardSequence': 0, 'winPctg': 0.6, 'wins': 15}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 15, 'conferenceL10Sequence': 4, 'conferenceName': 'Western', 'conferenceRoadSequence': 1, 'conferenceSequence': 5, 'date': '2025-12-01', 'divisionAbbrev': 'P', 'divisionHomeSequence': 7, 'divisionL10Sequence': 1, 'divisionName': 'Pacific', 'divisionRoadSequence': 1, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': -2, 'goalDifferentialPctg': -0.08, 'goalAgainst': 70, 'goalFor': 68, 'goalsForPctg': 2.72, 'homeGamesPlayed': 10, 'homeGoalDifferential': -9, 'homeGoalsAgainst': 29, 'homeGoalsFor': 20, 'homeLosses': 4, 'homeOtLosses': 3, 'homePoints': 9, 'homeRegulationPlusOtWins': 3, 'homeRegulationWins': 2, 'homeTies': 0, 'homeWins': 3, 'l10GamesPlayed': 10, 'l10GoalDifferential': 5, 'l10GoalsAgainst': 21, 'l10GoalsFor': 26, 'l10Losses': 1, 'l10OtLosses': 3, 'l10Points': 15, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 4, 'l10Ties': 0, 'l10Wins': 6, 'leagueHomeSequence': 30, 'leagueL10Sequence': 6, 'leagueRoadSequence': 2, 'leagueSequence': 10, 'losses': 6, 'otLosses': 7, 'placeName': {'default': 'Los Angeles'}, 'pointPctg': 0.62, 'points': 31, 'regulationPlusOtWinPctg': 0.44, 'regulationPlusOtWins': 11, 'regulationWinPctg': 0.28, 'regulationWins': 7, 'roadGamesPlayed': 15, 'roadGoalDifferential': 7, 'roadGoalsAgainst': 41, 'roadGoalsFor': 48, 'roadLosses': 2, 'roadOtLosses': 4, 'roadPoints': 22, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 5, 'roadTies': 0, 'roadWins': 9, 'seasonId': 20252026, 'shootoutLosses': 5, 'shootoutWins': 1, 'streakCode': 'W', 'streakCount': 1, 'teamName': {'default': 'Los Angeles Kings', 'fr': 'Kings de Los Angeles'}, 'teamCommonName': {'default': 'Kings'}, 'teamAbbrev': {'default': 'LAK'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/LAK_light.svg', 'ties': 0, 'waiversSequence': 24, 'wildcardSequence': 0, 'winPctg': 0.48, 'wins': 12}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 6, 'conferenceL10Sequence': 6, 'conferenceName': 'Western', 'conferenceRoadSequence': 6, 'conferenceSequence': 6, 'date': '2025-12-01', 'divisionAbbrev': 'P', 'divisionHomeSequence': 3, 'divisionL10Sequence': 3, 'divisionName': 'Pacific', 'divisionRoadSequence': 4, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 0, 'goalDifferentialPctg': 0.0, 'goalAgainst': 76, 'goalFor': 76, 'goalsForPctg': 3.04, 'homeGamesPlayed': 14, 'homeGoalDifferential': -1, 'homeGoalsAgainst': 47, 'homeGoalsFor': 46, 'homeLosses': 4, 'homeOtLosses': 4, 'homePoints': 16, 'homeRegulationPlusOtWins': 6, 'homeRegulationWins': 6, 'homeTies': 0, 'homeWins': 6, 'l10GamesPlayed': 10, 'l10GoalDifferential': -3, 'l10GoalsAgainst': 31, 'l10GoalsFor': 28, 'l10Losses': 2, 'l10OtLosses': 4, 'l

:

In [15]:
print(standings['standings'][0].keys())

dict_keys(['conferenceAbbrev', 'conferenceHomeSequence', 'conferenceL10Sequence', 'conferenceName', 'conferenceRoadSequence', 'conferenceSequence', 'date', 'divisionAbbrev', 'divisionHomeSequence', 'divisionL10Sequence', 'divisionName', 'divisionRoadSequence', 'divisionSequence', 'gameTypeId', 'gamesPlayed', 'goalDifferential', 'goalDifferentialPctg', 'goalAgainst', 'goalFor', 'goalsForPctg', 'homeGamesPlayed', 'homeGoalDifferential', 'homeGoalsAgainst', 'homeGoalsFor', 'homeLosses', 'homeOtLosses', 'homePoints', 'homeRegulationPlusOtWins', 'homeRegulationWins', 'homeTies', 'homeWins', 'l10GamesPlayed', 'l10GoalDifferential', 'l10GoalsAgainst', 'l10GoalsFor', 'l10Losses', 'l10OtLosses', 'l10Points', 'l10RegulationPlusOtWins', 'l10RegulationWins', 'l10Ties', 'l10Wins', 'leagueHomeSequence', 'leagueL10Sequence', 'leagueRoadSequence', 'leagueSequence', 'losses', 'otLosses', 'placeName', 'pointPctg', 'points', 'regulationPlusOtWinPctg', 'regulationPlusOtWins', 'regulationWinPctg', 'regulationWins', 'roadGamesPlayed', 'roadGoalDifferential', 'roadGoalsAgainst', 'roadGoalsFor', 'roadLosses', 'roadOtLosses', 'roadPoints', 'roadRegulationPlusOtWins', 'roadRegulationWins', 'roadTies', 'roadWins', 'seasonId', 'shootoutLosses', 'shootoutWins', 'streakCode', 'streakCount', 'teamName', 'teamCommonName', 'teamAbbrev', 'teamLogo', 'ties', 'waiversSequence', 'wildcardSequence', 'winPctg', 'wins'])

In [ ]:
import pandas as pd
print(standings['standings'])
for each in standings['standings']:
  print(each)

[{'conferenceAbbrev': 'W', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 1, 'conferenceName': 'Western', 'conferenceRoadSequence': 3, 'conferenceSequence': 1, 'date': '2025-12-01', 'divisionAbbrev': 'C', 'divisionHomeSequence': 1, 'divisionL10Sequence': 1, 'divisionName': 'Central', 'divisionRoadSequence': 2, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 48, 'goalDifferentialPctg': 1.92, 'goalAgainst': 55, 'goalFor': 103, 'goalsForPctg': 4.12, 'homeGamesPlayed': 12, 'homeGoalDifferential': 30, 'homeGoalsAgainst': 28, 'homeGoalsFor': 58, 'homeLosses': 0, 'homeOtLosses': 2, 'homePoints': 22, 'homeRegulationPlusOtWins': 10, 'homeRegulationWins': 10, 'homeTies': 0, 'homeWins': 10, 'l10GamesPlayed': 10, 'l10GoalDifferential': 27, 'l10GoalsAgainst': 17, 'l10GoalsFor': 44, 'l10Losses': 0, 'l10OtLosses': 1, 'l10Points': 19, 'l10RegulationPlusOtWins': 9, 'l10RegulationWins': 8, 'l10Ties': 0, 'l10Wins': 9, 'leagueHomeSequence': 1, 'leagueL10Sequence': 1, 'leagueRoadSequence': 4, 'leagueSequence': 1, 'losses': 1, 'otLosses': 6, 'placeName': {'default': 'Colorado'}, 'pointPctg': 0.84, 'points': 42, 'regulationPlusOtWinPctg': 0.72, 'regulationPlusOtWins': 18, 'regulationWinPctg': 0.68, 'regulationWins': 17, 'roadGamesPlayed': 13, 'roadGoalDifferential': 18, 'roadGoalsAgainst': 27, 'roadGoalsFor': 45, 'roadLosses': 1, 'roadOtLosses': 4, 'roadPoints': 20, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 7, 'roadTies': 0, 'roadWins': 8, 'seasonId': 20252026, 'shootoutLosses': 3, 'shootoutWins': 0, 'streakCode': 'W', 'streakCount': 1, 'teamName': {'default': 'Colorado Avalanche', 'fr': 'Avalanche du Colorado'}, 'teamCommonName': {'default': 'Avalanche'}, 'teamAbbrev': {'default': 'COL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/COL_light.svg', 'ties': 0, 'waiversSequence': 32, 'wildcardSequence': 0, 'winPctg': 0.72, 'wins': 18}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 5, 'conferenceL10Sequence': 3, 'conferenceName': 'Western', 'conferenceRoadSequence': 2, 'conferenceSequence': 2, 'date': '2025-12-01', 'divisionAbbrev': 'C', 'divisionHomeSequence': 3, 'divisionL10Sequence': 3, 'divisionName': 'Central', 'divisionRoadSequence': 1, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 26, 'goalDifferential': 22, 'goalDifferentialPctg': 0.846154, 'goalAgainst': 71, 'goalFor': 93, 'goalsForPctg': 3.576923, 'homeGamesPlayed': 13, 'homeGoalDifferential': 7, 'homeGoalsAgainst': 36, 'homeGoalsFor': 43, 'homeLosses': 4, 'homeOtLosses': 1, 'homePoints': 17, 'homeRegulationPlusOtWins': 7, 'homeRegulationWins': 7, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 24, 'l10GoalsAgainst': 20, 'l10GoalsFor': 44, 'l10Losses': 1, 'l10OtLosses': 1, 'l10Points': 17, 'l10RegulationPlusOtWins': 8, 'l10RegulationWins': 7, 'l10Ties': 0, 'l10Wins': 8, 'leagueHomeSequence': 12, 'leagueL10Sequence': 3, 'leagueRoadSequence': 3, 'leagueSequence': 2, 'losses': 5, 'otLosses': 4, 'placeName': {'default': 'Dallas'}, 'pointPctg': 0.730769, 'points': 38, 'regulationPlusOtWinPctg': 0.576923, 'regulationPlusOtWins': 15, 'regulationWinPctg': 0.538462, 'regulationWins': 14, 'roadGamesPlayed': 13, 'roadGoalDifferential': 15, 'roadGoalsAgainst': 35, 'roadGoalsFor': 50, 'roadLosses': 1, 'roadOtLosses': 3, 'roadPoints': 21, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 7, 'roadTies': 0, 'roadWins': 9, 'seasonId': 20252026, 'shootoutLosses': 2, 'shootoutWins': 2, 'streakCode': 'W', 'streakCount': 4, 'teamName': {'default': 'Dallas Stars', 'fr': 'Stars de Dallas'}, 'teamCommonName': {'default': 'Stars'}, 'teamAbbrev': {'default': 'DAL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/DAL_light.svg', 'ties': 0, 'waiversSequence': 31, 'wildcardSequence': 0, 'winPctg': 0.653846, 'wins': 17}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 10, 'conferenceL10Sequence': 1, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 2, 'conferenceSequence': 1, 'date': '2025-12-01', 'divisionAbbrev': 'A', 'divisionHomeSequence': 6, 'divisionL10Sequence': 1, 'divisionName': 'Atlantic', 'divisionRoadSequence': 1, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 19, 'goalDifferentialPctg': 0.76, 'goalAgainst': 65, 'goalFor': 84, 'goalsForPctg': 3.36, 'homeGamesPlayed': 13, 'homeGoalDifferential': 4, 'homeGoalsAgainst': 36, 'homeGoalsFor': 40, 'homeLosses': 5, 'homeOtLosses': 0, 'homePoints': 16, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 5, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 14, 'l10GoalsAgainst': 24, 'l10GoalsFor': 38, 'l10Losses': 2, 'l10OtLosses': 0, 'l10Points': 16, 'l10RegulationPlusOtWins': 8, 'l10RegulationWins': 7, 'l10Ties': 0, 'l10Wins': 8, 'leagueHomeSequence': 15, 'leagueL10Sequence': 4, 'leagueRoadSequence': 5, 'leagueSequence': 3, 'losses': 7, 'otLosses': 2, 'placeName': {'default': 'Tampa Bay'}, 'pointPctg': 0.68, 'points': 34, 'regulationPlusOtWinPctg': 0.64, 'regulationPlusOtWins': 16, 'regulationWinPctg': 0.52, 'regulationWins': 13, 'roadGamesPlayed': 12, 'roadGoalDifferential': 15, 'roadGoalsAgainst': 29, 'roadGoalsFor': 44, 'roadLosses': 2, 'roadOtLosses': 2, 'roadPoints': 18, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 8, 'roadTies': 0, 'roadWins': 8, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 0, 'streakCode': 'W', 'streakCount': 7, 'teamName': {'default': 'Tampa Bay Lightning', 'fr': 'Lightning de Tampa Bay'}, 'teamCommonName': {'default': 'Lightning'}, 'teamAbbrev': {'default': 'TBL'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/TBL_light.svg', 'ties': 0, 'waiversSequence': 30, 'wildcardSequence': 0, 'winPctg': 0.64, 'wins': 16}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 7, 'conferenceL10Sequence': 4, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 3, 'conferenceSequence': 2, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 4, 'divisionL10Sequence': 3, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 2, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 16, 'goalDifferentialPctg': 0.64, 'goalAgainst': 70, 'goalFor': 86, 'goalsForPctg': 3.44, 'homeGamesPlayed': 12, 'homeGoalDifferential': 9, 'homeGoalsAgainst': 36, 'homeGoalsFor': 45, 'homeLosses': 3, 'homeOtLosses': 1, 'homePoints': 17, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 5, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': -1, 'l10GoalsAgainst': 28, 'l10GoalsFor': 27, 'l10Losses': 3, 'l10OtLosses': 2, 'l10Points': 12, 'l10RegulationPlusOtWins': 5, 'l10RegulationWins': 3, 'l10Ties': 0, 'l10Wins': 5, 'leagueHomeSequence': 11, 'leagueL10Sequence': 11, 'leagueRoadSequence': 6, 'leagueSequence': 4, 'losses': 7, 'otLosses': 2, 'placeName': {'default': 'Carolina', 'fr': 'Caroline'}, 'pointPctg': 0.68, 'points': 34, 'regulationPlusOtWinPctg': 0.6, 'regulationPlusOtWins': 15, 'regulationWinPctg': 0.44, 'regulationWins': 11, 'roadGamesPlayed': 13, 'roadGoalDifferential': 7, 'roadGoalsAgainst': 34, 'roadGoalsFor': 41, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 17, 'roadRegulationPlusOtWins': 7, 'roadRegulationWins': 6, 'roadTies': 0, 'roadWins': 8, 'seasonId': 20252026, 'shootoutLosses': 1, 'shootoutWins': 1, 'streakCode': 'W', 'streakCount': 2, 'teamName': {'default': 'Carolina Hurricanes', 'fr': 'Hurricanes de la Caroline'}, 'teamCommonName': {'default': 'Hurricanes'}, 'teamAbbrev': {'default': 'CAR'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/CAR_light.svg', 'ties': 0, 'waiversSequence': 29, 'wildcardSequence': 0, 'winPctg': 0.64, 'wins': 16}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 1, 'conferenceL10Sequence': 9, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 7, 'conferenceSequence': 3, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 1, 'divisionL10Sequence': 7, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 5, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 6, 'goalDifferentialPctg': 0.24, 'goalAgainst': 74, 'goalFor': 80, 'goalsForPctg': 3.2, 'homeGamesPlayed': 11, 'homeGoalDifferential': 11, 'homeGoalsAgainst': 26, 'homeGoalsFor': 37, 'homeLosses': 1, 'homeOtLosses': 1, 'homePoints': 19, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 5, 'homeTies': 0, 'homeWins': 9, 'l10GamesPlayed': 10, 'l10GoalDifferential': -2, 'l10GoalsAgainst': 30, 'l10GoalsFor': 28, 'l10Losses': 4, 'l10OtLosses': 1, 'l10Points': 11, 'l10RegulationPlusOtWins': 4, 'l10RegulationWins': 2, 'l10Ties': 0, 'l10Wins': 5, 'leagueHomeSequence': 3, 'leagueL10Sequence': 17, 'leagueRoadSequence': 14, 'leagueSequence': 5, 'losses': 8, 'otLosses': 1, 'placeName': {'default': 'New Jersey'}, 'pointPctg': 0.66, 'points': 33, 'regulationPlusOtWinPctg': 0.56, 'regulationPlusOtWins': 14, 'regulationWinPctg': 0.4, 'regulationWins': 10, 'roadGamesPlayed': 14, 'roadGoalDifferential': -5, 'roadGoalsAgainst': 48, 'roadGoalsFor': 43, 'roadLosses': 7, 'roadOtLosses': 0, 'roadPoints': 14, 'roadRegulationPlusOtWins': 6, 'roadRegulationWins': 5, 'roadTies': 0, 'roadWins': 7, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 2, 'streakCode': 'L', 'streakCount': 1, 'teamName': {'default': 'New Jersey Devils', 'fr': 'Devils du New Jersey'}, 'teamCommonName': {'default': 'Devils'}, 'teamAbbrev': {'default': 'NJD'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/NJD_light.svg', 'ties': 0, 'waiversSequence': 28, 'wildcardSequence': 0, 'winPctg': 0.64, 'wins': 16}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 2, 'conferenceL10Sequence': 2, 'conferenceName': 'Western', 'conferenceRoadSequence': 8, 'conferenceSequence': 3, 'date': '2025-12-01', 'divisionAbbrev': 'C', 'divisionHomeSequence': 2, 'divisionL10Sequence': 2, 'divisionName': 'Central', 'divisionRoadSequence': 4, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 26, 'goalDifferential': 5, 'goalDifferentialPctg': 0.192308, 'goalAgainst': 72, 'goalFor': 77, 'goalsForPctg': 2.961538, 'homeGamesPlayed': 15, 'homeGoalDifferential': -2, 'homeGoalsAgainst': 46, 'homeGoalsFor': 44, 'homeLosses': 3, 'homeOtLosses': 4, 'homePoints': 20, 'homeRegulationPlusOtWins': 5, 'homeRegulationWins': 3, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 14, 'l10GoalsAgainst': 15, 'l10GoalsFor': 29, 'l10Losses': 0, 'l10OtLosses': 2, 'l10Points': 18, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 4, 'l10Ties': 0, 'l10Wins': 8, 'leagueHomeSequence': 2, 'leagueL10Sequence': 2, 'leagueRoadSequence': 18, 'leagueSequence': 6, 'losses': 7, 'otLosses': 5, 'placeName': {'default': 'Minnesota'}, 'pointPctg': 0.634615, 'points': 33, 'regulationPlusOtWinPctg': 0.423077, 'regulationPlusOtWins': 11, 'regulationWinPctg': 0.307692, 'regulationWins': 8, 'roadGamesPlayed': 11, 'roadGoalDifferential': 7, 'roadGoalsAgainst': 26, 'roadGoalsFor': 33, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 6, 'roadRegulationWins': 5, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 1, 'shootoutWins': 3, 'streakCode': 'OT', 'streakCount': 1, 'teamName': {'default': 'Minnesota Wild', 'fr': 'Wild du Minnesota'}, 'teamCommonName': {'default': 'Wild'}, 'teamAbbrev': {'default': 'MIN'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/MIN_light.svg', 'ties': 0, 'waiversSequence': 26, 'wildcardSequence': 0, 'winPctg': 0.538462, 'wins': 14}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 2, 'conferenceL10Sequence': 2, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 10, 'conferenceSequence': 4, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 2, 'divisionL10Sequence': 1, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 7, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 26, 'goalDifferential': 19, 'goalDifferentialPctg': 0.730769, 'goalAgainst': 69, 'goalFor': 88, 'goalsForPctg': 3.384615, 'homeGamesPlayed': 15, 'homeGoalDifferential': 10, 'homeGoalsAgainst': 41, 'homeGoalsFor': 51, 'homeLosses': 5, 'homeOtLosses': 1, 'homePoints': 19, 'homeRegulationPlusOtWins': 9, 'homeRegulationWins': 8, 'homeTies': 0, 'homeWins': 9, 'l10GamesPlayed': 10, 'l10GoalDifferential': 12, 'l10GoalsAgainst': 30, 'l10GoalsFor': 42, 'l10Losses': 2, 'l10OtLosses': 1, 'l10Points': 15, 'l10RegulationPlusOtWins': 7, 'l10RegulationWins': 7, 'l10Ties': 0, 'l10Wins': 7, 'leagueHomeSequence': 4, 'leagueL10Sequence': 5, 'leagueRoadSequence': 17, 'leagueSequence': 7, 'losses': 9, 'otLosses': 2, 'placeName': {'default': 'Washington'}, 'pointPctg': 0.615385, 'points': 32, 'regulationPlusOtWinPctg': 0.576923, 'regulationPlusOtWins': 15, 'regulationWinPctg': 0.538462, 'regulationWins': 14, 'roadGamesPlayed': 11, 'roadGoalDifferential': 9, 'roadGoalsAgainst': 28, 'roadGoalsFor': 37, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 6, 'roadRegulationWins': 6, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 2, 'shootoutWins': 0, 'streakCode': 'W', 'streakCount': 4, 'teamName': {'default': 'Washington Capitals', 'fr': 'Capitals de Washington'}, 'teamCommonName': {'default': 'Capitals'}, 'teamAbbrev': {'default': 'WSH'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/WSH_secondary_light.svg', 'ties': 0, 'waiversSequence': 23, 'wildcardSequence': 0, 'winPctg': 0.576923, 'wins': 15}, {'conferenceAbbrev': 'E', 'conferenceHomeSequence': 4, 'conferenceL10Sequence': 3, 'conferenceName': 'Eastern', 'conferenceRoadSequence': 11, 'conferenceSequence': 5, 'date': '2025-12-01', 'divisionAbbrev': 'M', 'divisionHomeSequence': 3, 'divisionL10Sequence': 2, 'divisionName': 'Metropolitan', 'divisionRoadSequence': 8, 'divisionSequence': 4, 'gameTypeId': 2, 'gamesPlayed': 24, 'goalDifferential': 6, 'goalDifferentialPctg': 0.25, 'goalAgainst': 67, 'goalFor': 73, 'goalsForPctg': 3.041667, 'homeGamesPlayed': 13, 'homeGoalDifferential': 7, 'homeGoalsAgainst': 33, 'homeGoalsFor': 40, 'homeLosses': 3, 'homeOtLosses': 2, 'homePoints': 18, 'homeRegulationPlusOtWins': 6, 'homeRegulationWins': 4, 'homeTies': 0, 'homeWins': 8, 'l10GamesPlayed': 10, 'l10GoalDifferential': 1, 'l10GoalsAgainst': 31, 'l10GoalsFor': 32, 'l10Losses': 2, 'l10OtLosses': 2, 'l10Points': 14, 'l10RegulationPlusOtWins': 4, 'l10RegulationWins': 3, 'l10Ties': 0, 'l10Wins': 6, 'leagueHomeSequence': 8, 'leagueL10Sequence': 7, 'leagueRoadSequence': 19, 'leagueSequence': 8, 'losses': 7, 'otLosses': 3, 'placeName': {'default': 'Philadelphia', 'fr': 'Philadelphie'}, 'pointPctg': 0.645833, 'points': 31, 'regulationPlusOtWinPctg': 0.375, 'regulationPlusOtWins': 9, 'regulationWinPctg': 0.291667, 'regulationWins': 7, 'roadGamesPlayed': 11, 'roadGoalDifferential': -1, 'roadGoalsAgainst': 34, 'roadGoalsFor': 33, 'roadLosses': 4, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 3, 'roadRegulationWins': 3, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 5, 'streakCode': 'W', 'streakCount': 3, 'teamName': {'default': 'Philadelphia Flyers', 'fr': 'Flyers de Philadelphie'}, 'teamCommonName': {'default': 'Flyers'}, 'teamAbbrev': {'default': 'PHI'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/PHI_light.svg', 'ties': 0, 'waiversSequence': 27, 'wildcardSequence': 1, 'winPctg': 0.583333, 'wins': 14}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 4, 'conferenceL10Sequence': 14, 'conferenceName': 'Western', 'conferenceRoadSequence': 10, 'conferenceSequence': 4, 'date': '2025-12-01', 'divisionAbbrev': 'P', 'divisionHomeSequence': 2, 'divisionL10Sequence': 7, 'divisionName': 'Pacific', 'divisionRoadSequence': 6, 'divisionSequence': 1, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 9, 'goalDifferentialPctg': 0.36, 'goalAgainst': 83, 'goalFor': 92, 'goalsForPctg': 3.68, 'homeGamesPlayed': 12, 'homeGoalDifferential': 13, 'homeGoalsAgainst': 34, 'homeGoalsFor': 47, 'homeLosses': 3, 'homeOtLosses': 0, 'homePoints': 18, 'homeRegulationPlusOtWins': 8, 'homeRegulationWins': 6, 'homeTies': 0, 'homeWins': 9, 'l10GamesPlayed': 10, 'l10GoalDifferential': -8, 'l10GoalsAgainst': 37, 'l10GoalsFor': 29, 'l10Losses': 6, 'l10OtLosses': 0, 'l10Points': 8, 'l10RegulationPlusOtWins': 3, 'l10RegulationWins': 1, 'l10Ties': 0, 'l10Wins': 4, 'leagueHomeSequence': 7, 'leagueL10Sequence': 29, 'leagueRoadSequence': 21, 'leagueSequence': 9, 'losses': 9, 'otLosses': 1, 'placeName': {'default': 'Anaheim'}, 'pointPctg': 0.62, 'points': 31, 'regulationPlusOtWinPctg': 0.52, 'regulationPlusOtWins': 13, 'regulationWinPctg': 0.36, 'regulationWins': 9, 'roadGamesPlayed': 13, 'roadGoalDifferential': -4, 'roadGoalsAgainst': 49, 'roadGoalsFor': 45, 'roadLosses': 6, 'roadOtLosses': 1, 'roadPoints': 13, 'roadRegulationPlusOtWins': 5, 'roadRegulationWins': 3, 'roadTies': 0, 'roadWins': 6, 'seasonId': 20252026, 'shootoutLosses': 0, 'shootoutWins': 2, 'streakCode': 'L', 'streakCount': 1, 'teamName': {'default': 'Anaheim Ducks', 'fr': "Ducks d'Anaheim"}, 'teamCommonName': {'default': 'Ducks'}, 'teamAbbrev': {'default': 'ANA'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/ANA_light.svg', 'ties': 0, 'waiversSequence': 25, 'wildcardSequence': 0, 'winPctg': 0.6, 'wins': 15}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 15, 'conferenceL10Sequence': 4, 'conferenceName': 'Western', 'conferenceRoadSequence': 1, 'conferenceSequence': 5, 'date': '2025-12-01', 'divisionAbbrev': 'P', 'divisionHomeSequence': 7, 'divisionL10Sequence': 1, 'divisionName': 'Pacific', 'divisionRoadSequence': 1, 'divisionSequence': 2, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': -2, 'goalDifferentialPctg': -0.08, 'goalAgainst': 70, 'goalFor': 68, 'goalsForPctg': 2.72, 'homeGamesPlayed': 10, 'homeGoalDifferential': -9, 'homeGoalsAgainst': 29, 'homeGoalsFor': 20, 'homeLosses': 4, 'homeOtLosses': 3, 'homePoints': 9, 'homeRegulationPlusOtWins': 3, 'homeRegulationWins': 2, 'homeTies': 0, 'homeWins': 3, 'l10GamesPlayed': 10, 'l10GoalDifferential': 5, 'l10GoalsAgainst': 21, 'l10GoalsFor': 26, 'l10Losses': 1, 'l10OtLosses': 3, 'l10Points': 15, 'l10RegulationPlusOtWins': 6, 'l10RegulationWins': 4, 'l10Ties': 0, 'l10Wins': 6, 'leagueHomeSequence': 30, 'leagueL10Sequence': 6, 'leagueRoadSequence': 2, 'leagueSequence': 10, 'losses': 6, 'otLosses': 7, 'placeName': {'default': 'Los Angeles'}, 'pointPctg': 0.62, 'points': 31, 'regulationPlusOtWinPctg': 0.44, 'regulationPlusOtWins': 11, 'regulationWinPctg': 0.28, 'regulationWins': 7, 'roadGamesPlayed': 15, 'roadGoalDifferential': 7, 'roadGoalsAgainst': 41, 'roadGoalsFor': 48, 'roadLosses': 2, 'roadOtLosses': 4, 'roadPoints': 22, 'roadRegulationPlusOtWins': 8, 'roadRegulationWins': 5, 'roadTies': 0, 'roadWins': 9, 'seasonId': 20252026, 'shootoutLosses': 5, 'shootoutWins': 1, 'streakCode': 'W', 'streakCount': 1, 'teamName': {'default': 'Los Angeles Kings', 'fr': 'Kings de Los Angeles'}, 'teamCommonName': {'default': 'Kings'}, 'teamAbbrev': {'default': 'LAK'}, 'teamLogo': 'https://assets.nhle.com/logos/nhl/svg/LAK_light.svg', 'ties': 0, 'waiversSequence': 24, 'wildcardSequence': 0, 'winPctg': 0.48, 'wins': 12}, {'conferenceAbbrev': 'W', 'conferenceHomeSequence': 6, 'conferenceL10Sequence': 6, 'conferenceName': 'Western', 'conferenceRoadSequence': 6, 'conferenceSequence': 6, 'date': '2025-12-01', 'divisionAbbrev': 'P', 'divisionHomeSequence': 3, 'divisionL10Sequence': 3, 'divisionName': 'Pacific', 'divisionRoadSequence': 4, 'divisionSequence': 3, 'gameTypeId': 2, 'gamesPlayed': 25, 'goalDifferential': 0, 'goalDifferentialPctg': 0.0, 'goalAgainst': 76, 'goalFor': 76, 'goalsForPctg': 3.04, 'homeGamesPlayed': 14, 'homeGoalDifferential': -1, 'homeGoalsAgainst': 47, 'homeGoalsFor': 46, 'homeLosses': 4, 'homeOtLosses': 4, 'homePoints': 16, 'homeRegulationPlusOtWins': 6, 'homeRegulationWins': 6, 'homeTies': 0, 'homeWins': 6, 'l10GamesPlayed': 10, 'l10GoalDifferential': -3, 'l10GoalsAgainst': 31, 'l10GoalsFor': 28, 'l10Losses': 2, 'l10OtLosses': 4, 'l10Points': 12, 'l10RegulationPlusOtWins': 4, 'l10RegulationWins': 4, 'l10Ties': 0, 'l10Wi

:

: